# Generated by Django 3.1.3 on 2023-05-02 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquors', '0002_auto_20230502_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquor',
            name='caducidad',
            field=models.DateField(default=datetime.datetime(2023, 8, 2, 14, 29, 28, 909319)),
        ),
    ]
