# Generated by Django 3.1.3 on 2023-05-29 20:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('liquors', '0003_auto_20230502_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquor',
            name='url',
        ),
        migrations.AddField(
            model_name='liquor',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='liquor',
            name='caducidad',
            field=models.DateField(default=datetime.datetime(2023, 8, 29, 14, 33, 35, 591972)),
        ),
    ]
