# Generated by Django 3.1.3 on 2023-05-29 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquors', '0005_auto_20230529_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='link',
            new_name='liquor',
        ),
        migrations.AlterField(
            model_name='liquor',
            name='caducidad',
            field=models.DateField(default=datetime.datetime(2023, 8, 29, 15, 29, 56, 515699)),
        ),
    ]
